# Generated by Django 3.1.4 on 2021-05-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('breedName', models.TextField()),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('color', models.TextField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('length', models.IntegerField()),
                ('sellerId', models.IntegerField()),
                ('sellerName', models.TextField()),
                ('longDescription', models.TextField()),
                ('breedId', models.IntegerField()),
            ],
        ),
    ]
